name = "numbers"
defaultTargets = ["Numbers"]
testDriver = "NumbersTest"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "nightly-testing-2024-05-25"

[[lean_lib]]
name = "Numbers"

[[lean_lib]]
name = "NumbersTest"
globs = ["NumbersTest.+"]
